# (C) 2016 Chris Liechti <cliechti@gmx.net>
# SPDX-License-Identifier:    BSD-3-Clause

language: python
cache: pip

python:
  - 3.9

install:
  - pip install -r requirements-travis.txt
  - pip install -e .

script:
  - python test/test_asyncio.py
